name: hellotangle-tests

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NodeJS / NPM Installation
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: cd ${{ runner.workspace }}/hellotangle/api && npm install

      - name: Tests
        if: ${{ success() }}
        run: cd ${{ runner.workspace }}/hellotangle/api && npm test
